name: material_anticheat
description: 物资验收反作弊应用——BY 南安市政路项目

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.5
  
  # 数据序列化
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # 网络请求
  dio: ^5.4.0
  
  # 文件路径
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # 日期时间
  intl: ^0.19.0
  
  # UI组件
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  
  # 文件选择
  file_picker: ^6.1.1
  
  # 日志
  logger: ^2.0.2
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # URL启动
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码生成 - 更新版本
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  
  flutter_lints: ^3.0.2

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true 