name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: 启用 Windows 桌面支持
      run: flutter config --enable-windows-desktop
      
    - name: 验证项目结构
      run: |
        echo "当前工作目录:"
        pwd
        echo "目录内容:"
        dir
        echo "检查pubspec.yaml:"
        if (Test-Path "pubspec.yaml") { echo "pubspec.yaml 存在" } else { echo "pubspec.yaml 不存在" }
      shell: powershell
      
    - name: 获取依赖
      run: flutter pub get
      
    - name: 分析代码
      run: flutter analyze
      continue-on-error: true
      
    - name: 构建 Windows 应用
      run: flutter build windows --release
      
    - name: 创建应用包
      run: |
        mkdir windows-app
        xcopy build\windows\x64\runner\Release windows-app\ /E /I
      shell: cmd
        
    - name: 压缩应用
      run: |
        Compress-Archive -Path windows-app\* -DestinationPath 物资anticheat-windows.zip
      shell: powershell
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: 物资anticheat-windows.zip
        
    - name: 创建发布 (如果是tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: 物资anticheat-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 